name: deviceops-hello-world
version: '0.0.1'
summary: README.md
description: Example of snapped Node.js application for communications with Nordic Thingy:52
confinement: strict
grade: devel

parts:
  deviceops-hello-world:
    plugin: nodejs
    source: .
    build-packages:
      - libudev-dev
      - libbluetooth-dev
      - python
      - g++
      - make
      - bluez

apps:
  deviceops-hello-world:
    command: bin/deviceops-hello-world
    daemon: simple
    restart-condition: always
    plugs:
      - home
      - network
      - bluetooth-control
